# Generated by Django 5.0.6 on 2024-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingmessage_owner_mailingsettings_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('change_mailingsettings_setting_status', 'Can change mailingsettings setting_status')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройка рассылок'},
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец рассылки'),
        ),
    ]
