# Generated by Django 5.0.6 on 2024-07-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingstatus',
            old_name='status',
            new_name='sending_status',
        ),
    ]
